//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 11:56:47 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiSchoolWeb.Entities;
using SBiSchoolWeb.Data;


namespace SBiSchoolWeb.Business
{
    /// <summary>
    /// Exams business component.
    /// </summary>
    public partial class ExamsComponent
    {
        /// <summary>
        /// GetAllExams business method. 
        /// </summary>
        /// <returns>Returns a List<Exam> object.</returns>
        public List<Exam> GetAllExams()
        {
            List<Exam> result = default(List<Exam>);

            // Data access component declarations.
            ExamDAC examDAC = new ExamDAC();

            // Step 1 - Calling Select on ExamDAC.
            result = examDAC.Select();
            return result;

        }

        /// <summary>
        /// GetExam business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>Returns a Exam object.</returns>
        public Exam GetExam(int id)
        {
            Exam result = default(Exam);

            // Data access component declarations.
            ExamDAC examDAC = new ExamDAC();

            // Step 1 - Calling SelectById on ExamDAC.
            result = examDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// CreateExam business method. 
        /// </summary>
        /// <param name="exam">A exam value.</param>
        /// <returns>Returns a Exam object.</returns>
        public Exam CreateExam(Exam exam)
        {
            Exam result = default(Exam);

            // Data access component declarations.
            ExamDAC examDAC = new ExamDAC();

            // Step 1 - Calling Create on ExamDAC.
            result = examDAC.Create(exam);
            return result;

        }

        /// <summary>
        /// UpdateExam business method. 
        /// </summary>
        /// <param name="exam">A exam value.</param>
        public void UpdateExam(Exam exam)
        {
            // Data access component declarations.
            ExamDAC examDAC = new ExamDAC();

            // Step 1 - Calling UpdateById on ExamDAC.
            examDAC.UpdateById(exam);

        }

        /// <summary>
        /// DeleteExam business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteExam(int id)
        {
            // Data access component declarations.
            ExamDAC examDAC = new ExamDAC();

            // Step 1 - Calling DeleteById on ExamDAC.
            examDAC.DeleteById(id);

        }

        /// <summary>
        /// GetAllRegisteredStudents business method. 
        /// </summary>
        /// <returns>Returns a List<StudentExam> object.</returns>
        public List<StudentExam> GetAllRegisteredStudents()
        {
            List<StudentExam> result = default(List<StudentExam>);

            // Data access component declarations.
            StudentExamDAC StudentExamDAC = new StudentExamDAC();

            // Step 1 - Calling Select on StudentExamDAC.
            result = StudentExamDAC.Select();
            return result;

        }

        /// <summary>
        /// GetAllMarkSheet business method. 
        /// </summary>
        /// <returns>Returns a List<StudentExam> object.</returns>
        public List<StudentExam> GetAllMarkSheet()
        {
            List<StudentExam> result = default(List<StudentExam>);

            // Data access component declarations.
            StudentExamDAC StudentExamDAC = new StudentExamDAC();

            // Step 1 - Calling Select on StudentExamDAC.
            result = StudentExamDAC.Select();
            return result;

        }

        /// <summary>
        /// GetAllProcessedExams business method. 
        /// </summary>
        /// <returns>Returns a List<StudentsExamResults_Temp> object.</returns>
        public List<StudentsExamResults_Temp> GetAllProcessedExams()
        {
            List<StudentsExamResults_Temp> result = default(List<StudentsExamResults_Temp>);

            // Data access component declarations.
            StudentsExamResults_TempDAC StudentsExamResults_TempDAC = new StudentsExamResults_TempDAC();

            // Step 1 - Calling Select on StudentsExamResults_TempDAC.
            result = StudentsExamResults_TempDAC.Select();
            return result;

        }

        /// <summary>
        /// GetAllProgressResultsList business method. 
        /// </summary>
        /// <returns>Returns a List<StudentProgresses_Temp> object.</returns>
        public List<StudentProgresses_Temp> GetAllProgressResultsList()
        {
            List<StudentProgresses_Temp> result = default(List<StudentProgresses_Temp>);

            // Data access component declarations.
            StudentProgresses_TempDAC StudentProgresses_TempDAC = new StudentProgresses_TempDAC();

            // Step 1 - Calling Select on StudentProgresses_TempDAC.
            result = StudentProgresses_TempDAC.Select();
            return result;

        }

        /// <summary>
        /// GetAllRegisteredExams business method. 
        /// </summary>
        /// <returns>Returns a List<RegisteredExam> object.</returns>
        public List<RegisteredExam> GetAllRegisteredExams()
        {
            List<RegisteredExam> result = default(List<RegisteredExam>);

            // Data access component declarations.
            RegisteredExamDAC RegisteredExamDAC = new RegisteredExamDAC();

            // Step 1 - Calling Select on RegisteredExamDAC.
            result = RegisteredExamDAC.Select();
            return result;

        }






























































































    }
}
