//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/19/2014 14:02:10 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiSchoolWeb.Entities;
using SBiSchoolWeb.Data;


namespace SBiSchoolWeb.Business
{
    /// <summary>
    /// Fees business component.
    /// </summary>
    public partial class FeesComponent
    {
        /// <summary>
        /// GetAllFeeStructure business method. 
        /// </summary>
        /// <returns>Returns a List<FeesStructure> object.</returns>
        public List<FeesStructure> GetAllFeeStructure()
        {
            List<FeesStructure> result = default(List<FeesStructure>);

            // Data access component declarations.
            FeesStructureDAC feesStructureDAC = new FeesStructureDAC();

            // Step 1 - Calling Select on FeesStructureDAC.
            result = feesStructureDAC.Select();
            return result;

        }

        /// <summary>
        /// GetAllAdmissions business method. 
        /// </summary>
        /// <returns>Returns a List<Student> object.</returns>
        public List<Student> GetAllAdmissions()
        {
            List<Student> result = default(List<Student>);

            // Data access component declarations.
            StudentDAC StudentDAC = new StudentDAC();

            // Step 1 - Calling Select on StudentDAC.
            result = StudentDAC.Select();
            return result;

        }

        /// <summary>
        /// GetAllFeeStructureAcademics business method. 
        /// </summary>
        /// <returns>Returns a List<FeeStructureAcademic> object.</returns>
        public List<FeeStructureAcademic> GetAllFeeStructureAcademics()
        {
            List<FeeStructureAcademic> result = default(List<FeeStructureAcademic>);

            // Data access component declarations.
            FeeStructureAcademicDAC FeeStructureAcademicDAC = new FeeStructureAcademicDAC();

            // Step 1 - Calling Select on FeeStructureAcademicDAC.
            result = FeeStructureAcademicDAC.Select();
            return result;

        }

        /// <summary>
        /// GetAllFeeStructureOthers business method. 
        /// </summary>
        /// <returns>Returns a List<FeeStructureOther> object.</returns>
        public List<FeeStructureOther> GetAllFeeStructureOthers()
        {
            List<FeeStructureOther> result = default(List<FeeStructureOther>);

            // Data access component declarations.
            FeeStructureOtherDAC FeeStructureOtherDAC = new FeeStructureOtherDAC();

            // Step 1 - Calling Select on FeeStructureOtherDAC.
            result = FeeStructureOtherDAC.Select();
            return result;

        }









    }
}
