//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 08:44:11 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiSchoolWeb.Entities;
using SBiSchoolWeb.Data;


namespace SBiSchoolWeb.Business
{
    /// <summary>
    /// Students business component.
    /// </summary>
    public partial class StudentsComponent
    {
        /// <summary>
        /// GetAllStudents business method. 
        /// </summary>
        /// <returns>Returns a List<Student> object.</returns>
        public List<Student> GetAllStudents()
        {
            List<Student> result = default(List<Student>);

            // Data access component declarations.
            StudentDAC studentDAC = new StudentDAC();

            // Step 1 - Calling Select on StudentDAC.
            result = studentDAC.Select();
            return result;

        }

        /// <summary>
        /// GetStudent business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>Returns a Student object.</returns>
        public Student GetStudent(int id)
        {
            Student result = default(Student);

            // Data access component declarations.
            StudentDAC studentDAC = new StudentDAC();

            // Step 1 - Calling SelectById on StudentDAC.
            result = studentDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// CreateStudent business method. 
        /// </summary>
        /// <param name="student">A student value.</param>
        /// <returns>Returns a Student object.</returns>
        public Student CreateStudent(Student student)
        {
            Student result = default(Student);

            // Data access component declarations.
            StudentDAC studentDAC = new StudentDAC();

            // Step 1 - Calling Create on StudentDAC.
            result = studentDAC.Create(student);
            return result;

        }

        /// <summary>
        /// UpdateStudent business method. 
        /// </summary>
        /// <param name="student">A student value.</param>
        public void UpdateStudent(Student student)
        {
            // Data access component declarations.
            StudentDAC studentDAC = new StudentDAC();

            // Step 1 - Calling UpdateById on StudentDAC.
            studentDAC.UpdateById(student);

        }

        /// <summary>
        /// DeleteStudent business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteStudent(int id)
        {
            // Data access component declarations.
            StudentDAC studentDAC = new StudentDAC();

            // Step 1 - Calling DeleteById on StudentDAC.
            studentDAC.DeleteById(id);

        }
    }
}
