//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 08:44:11 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiSchoolWeb.Entities;
using SBiSchoolWeb.Data;


namespace SBiSchoolWeb.Business
{
    /// <summary>
    /// Teachers business component.
    /// </summary>
    public partial class TeachersComponent
    {
        /// <summary>
        /// GetAllTeachers business method. 
        /// </summary>
        /// <returns>Returns a List<Teacher> object.</returns>
        public List<Teacher> GetAllTeachers()
        {
            List<Teacher> result = default(List<Teacher>);

            // Data access component declarations.
            TeacherDAC teacherDAC = new TeacherDAC();

            // Step 1 - Calling Select on TeacherDAC.
            result = teacherDAC.Select();
            return result;

        }

        /// <summary>
        /// GetTeacher business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>Returns a Teacher object.</returns>
        public Teacher GetTeacher(int id)
        {
            Teacher result = default(Teacher);

            // Data access component declarations.
            TeacherDAC teacherDAC = new TeacherDAC();

            // Step 1 - Calling SelectById on TeacherDAC.
            result = teacherDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// CreateTeacher business method. 
        /// </summary>
        /// <param name="teacher">A teacher value.</param>
        /// <returns>Returns a Teacher object.</returns>
        public Teacher CreateTeacher(Teacher teacher)
        {
            Teacher result = default(Teacher);

            // Data access component declarations.
            TeacherDAC teacherDAC = new TeacherDAC();

            // Step 1 - Calling Create on TeacherDAC.
            result = teacherDAC.Create(teacher);
            return result;

        }

        /// <summary>
        /// UpdateTeacher business method. 
        /// </summary>
        /// <param name="teacher">A teacher value.</param>
        public void UpdateTeacher(Teacher teacher)
        {
            // Data access component declarations.
            TeacherDAC teacherDAC = new TeacherDAC();

            // Step 1 - Calling UpdateById on TeacherDAC.
            teacherDAC.UpdateById(teacher);

        }

        /// <summary>
        /// DeleteTeacher business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteTeacher(int id)
        {
            // Data access component declarations.
            TeacherDAC teacherDAC = new TeacherDAC();

            // Step 1 - Calling DeleteById on TeacherDAC.
            teacherDAC.DeleteById(id);

        }
    }
}
