//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:25:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSchoolWeb.Entities;

namespace SBiSchoolWeb.Data
{
    /// <summary>
    /// spAllowedRoleMenus data access component. Manages CRUD operations for the spAllowedRoleMenus table.
    /// </summary>
    public partial class spAllowedRoleMenusDAC 
    { 
        /// <summary>
        /// Returns a row from the spAllowedRoleMenus table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A spAllowedRoleMenus object with data populated from the database.</returns>
        public spAllowedRoleMenus SelectRight(int RoleId, int MenuItemId)
        {
            const string SQL_STATEMENT =
                "SELECT * " +
                "FROM dbo.spAllowedRoleMenus  " +
                "WHERE [RoleId]=@RoleId " +
                      "AND [RoleId]=@MenuItemId ";

            spAllowedRoleMenus spAllowedRoleMenus = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@RoleId", DbType.Int32, RoleId);
                db.AddInParameter(cmd, "@MenuItemId", DbType.Int32, MenuItemId);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new spAllowedRoleMenus
                        spAllowedRoleMenus = new spAllowedRoleMenus();

                        // Read values.
                        spAllowedRoleMenus.Id = base.GetDataValue<int>(dr, "Id");
                        spAllowedRoleMenus.RoleId = base.GetDataValue<int>(dr, "RoleId");
                        spAllowedRoleMenus.MenuItemId = base.GetDataValue<int>(dr, "MenuItemId");
                        spAllowedRoleMenus.Allowed = base.GetDataValue<bool>(dr, "Allowed");
                    }
                }
            }

            return spAllowedRoleMenus;
        }
         


    }
}

