//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:25:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSchoolWeb.Entities;

namespace SBiSchoolWeb.Data
{
    /// <summary>
    /// MarkSheetStudents data access component. Manages CRUD operations for the MarkSheetStudents table.
    /// </summary>
    public partial class MarkSheetStudentDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the MarkSheetStudents table.
        /// </summary>
        /// <param name="markSheetStudent">A MarkSheetStudent object.</param>
        /// <returns>An updated MarkSheetStudent object.</returns>
        public MarkSheetStudent Create(MarkSheetStudent markSheetStudent)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.MarkSheetStudents ([ExamId], [StudentId], [Mark], [LastModified], [ModifiedBy], [IsDeleted]) " +
                "VALUES(@ExamId, @StudentId, @Mark, @LastModified, @ModifiedBy, @IsDeleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ExamId", DbType.Int32, markSheetStudent.ExamId);
                db.AddInParameter(cmd, "@StudentId", DbType.Int32, markSheetStudent.StudentId);
                db.AddInParameter(cmd, "@Mark", DbType.Int32, markSheetStudent.Mark);
                db.AddInParameter(cmd, "@LastModified", DbType.DateTime, markSheetStudent.LastModified);
                db.AddInParameter(cmd, "@ModifiedBy", DbType.String, markSheetStudent.ModifiedBy);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, markSheetStudent.IsDeleted);

                // Get the primary key value.
                markSheetStudent.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return markSheetStudent;
        }

        /// <summary>
        /// Updates an existing row in the MarkSheetStudents table.
        /// </summary>
        /// <param name="markSheetStudent">A MarkSheetStudent entity object.</param>
        public void UpdateById(MarkSheetStudent markSheetStudent)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.MarkSheetStudents " +
                "SET " +
                    "[ExamId]=@ExamId, " +
                    "[StudentId]=@StudentId, " +
                    "[Mark]=@Mark, " +
                    "[LastModified]=@LastModified, " +
                    "[ModifiedBy]=@ModifiedBy, " +
                    "[IsDeleted]=@IsDeleted " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ExamId", DbType.Int32, markSheetStudent.ExamId);
                db.AddInParameter(cmd, "@StudentId", DbType.Int32, markSheetStudent.StudentId);
                db.AddInParameter(cmd, "@Mark", DbType.Int32, markSheetStudent.Mark);
                db.AddInParameter(cmd, "@LastModified", DbType.DateTime, markSheetStudent.LastModified);
                db.AddInParameter(cmd, "@ModifiedBy", DbType.String, markSheetStudent.ModifiedBy);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, markSheetStudent.IsDeleted);
                db.AddInParameter(cmd, "@Id", DbType.Int32, markSheetStudent.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the MarkSheetStudents table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.MarkSheetStudents " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the MarkSheetStudents table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A MarkSheetStudent object with data populated from the database.</returns>
        public MarkSheetStudent SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [ExamId], [StudentId], [Mark], [LastModified], [ModifiedBy], [IsDeleted] " +
                "FROM dbo.MarkSheetStudents  " +
                "WHERE [Id]=@Id ";

            MarkSheetStudent markSheetStudent = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new MarkSheetStudent
                        markSheetStudent = new MarkSheetStudent();

                        // Read values.
                        markSheetStudent.Id = base.GetDataValue<int>(dr, "Id");
                        markSheetStudent.ExamId = base.GetDataValue<int>(dr, "ExamId");
                        markSheetStudent.StudentId = base.GetDataValue<int>(dr, "StudentId");
                        markSheetStudent.Mark = base.GetDataValue<int>(dr, "Mark");
                        markSheetStudent.LastModified = base.GetDataValue<DateTime>(dr, "LastModified");
                        markSheetStudent.ModifiedBy = base.GetDataValue<string>(dr, "ModifiedBy");
                        markSheetStudent.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");
                    }
                }
            }

            return markSheetStudent;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the MarkSheetStudents table.
        /// </summary>
        /// <returns>A collection of MarkSheetStudent objects.</returns>		
        public List<MarkSheetStudent> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [ExamId], [StudentId], [Mark], [LastModified], [ModifiedBy], [IsDeleted] " +
                "FROM dbo.MarkSheetStudents ";

            List<MarkSheetStudent> result = new List<MarkSheetStudent>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new MarkSheetStudent
                        MarkSheetStudent markSheetStudent = new MarkSheetStudent();

                        // Read values.
                        markSheetStudent.Id = base.GetDataValue<int>(dr, "Id");
                        markSheetStudent.ExamId = base.GetDataValue<int>(dr, "ExamId");
                        markSheetStudent.StudentId = base.GetDataValue<int>(dr, "StudentId");
                        markSheetStudent.Mark = base.GetDataValue<int>(dr, "Mark");
                        markSheetStudent.LastModified = base.GetDataValue<DateTime>(dr, "LastModified");
                        markSheetStudent.ModifiedBy = base.GetDataValue<string>(dr, "ModifiedBy");
                        markSheetStudent.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");

                        // Add to List.
                        result.Add(markSheetStudent);
                    }
                }
            }

            return result;
        }
    }
}

