//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:25:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSchoolWeb.Entities;

namespace SBiSchoolWeb.Data
{
    /// <summary>
    /// PL_Level1 data access component. Manages CRUD operations for the PL_Level1 table.
    /// </summary>
    public partial class PL_Level1DAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the PL_Level1 table.
        /// </summary>
        /// <param name="pL_Level1">A PL_Level1 object.</param>
        /// <returns>An updated PL_Level1 object.</returns>
        public PL_Level1 Create(PL_Level1 pL_Level1)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.PL_Level1 ([Description], [ROrder], [PLGroup], [IsDeleted]) " +
                "VALUES(@Description, @ROrder, @PLGroup, @IsDeleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Description", DbType.String, pL_Level1.Description);
                db.AddInParameter(cmd, "@ROrder", DbType.Int32, pL_Level1.ROrder);
                db.AddInParameter(cmd, "@PLGroup", DbType.StringFixedLength, pL_Level1.PLGroup);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, pL_Level1.IsDeleted);

                // Get the primary key value.
                pL_Level1.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return pL_Level1;
        }

        /// <summary>
        /// Updates an existing row in the PL_Level1 table.
        /// </summary>
        /// <param name="pL_Level1">A PL_Level1 entity object.</param>
        public void UpdateById(PL_Level1 pL_Level1)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.PL_Level1 " +
                "SET " +
                    "[Description]=@Description, " +
                    "[ROrder]=@ROrder, " +
                    "[PLGroup]=@PLGroup, " +
                    "[IsDeleted]=@IsDeleted " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Description", DbType.String, pL_Level1.Description);
                db.AddInParameter(cmd, "@ROrder", DbType.Int32, pL_Level1.ROrder);
                db.AddInParameter(cmd, "@PLGroup", DbType.StringFixedLength, pL_Level1.PLGroup);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, pL_Level1.IsDeleted);
                db.AddInParameter(cmd, "@Id", DbType.Int32, pL_Level1.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the PL_Level1 table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.PL_Level1 " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the PL_Level1 table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A PL_Level1 object with data populated from the database.</returns>
        public PL_Level1 SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [Description], [ROrder], [PLGroup], [IsDeleted] " +
                "FROM dbo.PL_Level1  " +
                "WHERE [Id]=@Id ";

            PL_Level1 pL_Level1 = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new PL_Level1
                        pL_Level1 = new PL_Level1();

                        // Read values.
                        pL_Level1.Id = base.GetDataValue<int>(dr, "Id");
                        pL_Level1.Description = base.GetDataValue<string>(dr, "Description");
                        pL_Level1.ROrder = base.GetDataValue<int>(dr, "ROrder");
                        pL_Level1.PLGroup = base.GetDataValue<string>(dr, "PLGroup");
                        pL_Level1.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");
                    }
                }
            }

            return pL_Level1;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the PL_Level1 table.
        /// </summary>
        /// <returns>A collection of PL_Level1 objects.</returns>		
        public List<PL_Level1> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [Description], [ROrder], [PLGroup], [IsDeleted] " +
                "FROM dbo.PL_Level1 ";

            List<PL_Level1> result = new List<PL_Level1>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new PL_Level1
                        PL_Level1 pL_Level1 = new PL_Level1();

                        // Read values.
                        pL_Level1.Id = base.GetDataValue<int>(dr, "Id");
                        pL_Level1.Description = base.GetDataValue<string>(dr, "Description");
                        pL_Level1.ROrder = base.GetDataValue<int>(dr, "ROrder");
                        pL_Level1.PLGroup = base.GetDataValue<string>(dr, "PLGroup");
                        pL_Level1.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");

                        // Add to List.
                        result.Add(pL_Level1);
                    }
                }
            }

            return result;
        }
    }
}

