//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:25:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSchoolWeb.Entities;

namespace SBiSchoolWeb.Data
{
    /// <summary>
    /// ReportGroups data access component. Manages CRUD operations for the ReportGroups table.
    /// </summary>
    public partial class ReportGroupDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the ReportGroups table.
        /// </summary>
        /// <param name="reportGroup">A ReportGroup object.</param>
        /// <returns>An updated ReportGroup object.</returns>
        public ReportGroup Create(ReportGroup reportGroup)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.ReportGroups ([ReportGroup1], [IsDeleted]) " +
                "VALUES(@ReportGroup1, @IsDeleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ReportGroup1", DbType.String, reportGroup.ReportGroup1);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, reportGroup.IsDeleted);

                // Get the primary key value.
                reportGroup.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return reportGroup;
        }

        /// <summary>
        /// Updates an existing row in the ReportGroups table.
        /// </summary>
        /// <param name="reportGroup">A ReportGroup entity object.</param>
        public void UpdateById(ReportGroup reportGroup)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.ReportGroups " +
                "SET " +
                    "[ReportGroup1]=@ReportGroup1, " +
                    "[IsDeleted]=@IsDeleted " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ReportGroup1", DbType.String, reportGroup.ReportGroup1);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, reportGroup.IsDeleted);
                db.AddInParameter(cmd, "@Id", DbType.Int32, reportGroup.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the ReportGroups table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.ReportGroups " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the ReportGroups table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A ReportGroup object with data populated from the database.</returns>
        public ReportGroup SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [ReportGroup1], [IsDeleted] " +
                "FROM dbo.ReportGroups  " +
                "WHERE [Id]=@Id ";

            ReportGroup reportGroup = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new ReportGroup
                        reportGroup = new ReportGroup();

                        // Read values.
                        reportGroup.Id = base.GetDataValue<int>(dr, "Id");
                        reportGroup.ReportGroup1 = base.GetDataValue<string>(dr, "ReportGroup1");
                        reportGroup.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");
                    }
                }
            }

            return reportGroup;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the ReportGroups table.
        /// </summary>
        /// <returns>A collection of ReportGroup objects.</returns>		
        public List<ReportGroup> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [ReportGroup1], [IsDeleted] " +
                "FROM dbo.ReportGroups ";

            List<ReportGroup> result = new List<ReportGroup>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new ReportGroup
                        ReportGroup reportGroup = new ReportGroup();

                        // Read values.
                        reportGroup.Id = base.GetDataValue<int>(dr, "Id");
                        reportGroup.ReportGroup1 = base.GetDataValue<string>(dr, "ReportGroup1");
                        reportGroup.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");

                        // Add to List.
                        result.Add(reportGroup);
                    }
                }
            }

            return result;
        }
    }
}

