//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:25:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSchoolWeb.Entities;

namespace SBiSchoolWeb.Data
{
    /// <summary>
    /// StudentsExamResults_Temp data access component. Manages CRUD operations for the StudentsExamResults_Temp table.
    /// </summary>
    public partial class StudentsExamResults_TempDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the StudentsExamResults_Temp table.
        /// </summary>
        /// <param name="studentsExamResults_Temp">A StudentsExamResults_Temp object.</param>
        /// <returns>An updated StudentsExamResults_Temp object.</returns>
        public StudentsExamResults_Temp Create(StudentsExamResults_Temp studentsExamResults_Temp)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.StudentsExamResults_Temp ([StudentId], [Examid], [SchoolClassId], [TeacherId], [TotalMarks_Target], [TotalPoints_Target], [Position_Target], [MeanMarks_Target], [MeanGrade_Target], [TotalMarks], [TotalPoints], [Position], [MeanMarks], [MeanGrade], [ClassTeacherRemark], [HeadTeacherRemark], [Status], [IsDeleted]) " +
                "VALUES(@StudentId, @Examid, @SchoolClassId, @TeacherId, @TotalMarks_Target, @TotalPoints_Target, @Position_Target, @MeanMarks_Target, @MeanGrade_Target, @TotalMarks, @TotalPoints, @Position, @MeanMarks, @MeanGrade, @ClassTeacherRemark, @HeadTeacherRemark, @Status, @IsDeleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@StudentId", DbType.Int32, studentsExamResults_Temp.StudentId);
                db.AddInParameter(cmd, "@Examid", DbType.Int32, studentsExamResults_Temp.Examid);
                db.AddInParameter(cmd, "@SchoolClassId", DbType.Int32, studentsExamResults_Temp.SchoolClassId);
                db.AddInParameter(cmd, "@TeacherId", DbType.Int32, studentsExamResults_Temp.TeacherId);
                db.AddInParameter(cmd, "@TotalMarks_Target", DbType.Double, studentsExamResults_Temp.TotalMarks_Target);
                db.AddInParameter(cmd, "@TotalPoints_Target", DbType.Double, studentsExamResults_Temp.TotalPoints_Target);
                db.AddInParameter(cmd, "@Position_Target", DbType.Int32, studentsExamResults_Temp.Position_Target);
                db.AddInParameter(cmd, "@MeanMarks_Target", DbType.Double, studentsExamResults_Temp.MeanMarks_Target);
                db.AddInParameter(cmd, "@MeanGrade_Target", DbType.String, studentsExamResults_Temp.MeanGrade_Target);
                db.AddInParameter(cmd, "@TotalMarks", DbType.Double, studentsExamResults_Temp.TotalMarks);
                db.AddInParameter(cmd, "@TotalPoints", DbType.Double, studentsExamResults_Temp.TotalPoints);
                db.AddInParameter(cmd, "@Position", DbType.Int32, studentsExamResults_Temp.Position);
                db.AddInParameter(cmd, "@MeanMarks", DbType.Double, studentsExamResults_Temp.MeanMarks);
                db.AddInParameter(cmd, "@MeanGrade", DbType.String, studentsExamResults_Temp.MeanGrade);
                db.AddInParameter(cmd, "@ClassTeacherRemark", DbType.String, studentsExamResults_Temp.ClassTeacherRemark);
                db.AddInParameter(cmd, "@HeadTeacherRemark", DbType.String, studentsExamResults_Temp.HeadTeacherRemark);
                db.AddInParameter(cmd, "@Status", DbType.StringFixedLength, studentsExamResults_Temp.Status);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, studentsExamResults_Temp.IsDeleted);

                // Get the primary key value.
                studentsExamResults_Temp.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return studentsExamResults_Temp;
        }

        /// <summary>
        /// Updates an existing row in the StudentsExamResults_Temp table.
        /// </summary>
        /// <param name="studentsExamResults_Temp">A StudentsExamResults_Temp entity object.</param>
        public void UpdateById(StudentsExamResults_Temp studentsExamResults_Temp)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.StudentsExamResults_Temp " +
                "SET " +
                    "[StudentId]=@StudentId, " +
                    "[Examid]=@Examid, " +
                    "[SchoolClassId]=@SchoolClassId, " +
                    "[TeacherId]=@TeacherId, " +
                    "[TotalMarks_Target]=@TotalMarks_Target, " +
                    "[TotalPoints_Target]=@TotalPoints_Target, " +
                    "[Position_Target]=@Position_Target, " +
                    "[MeanMarks_Target]=@MeanMarks_Target, " +
                    "[MeanGrade_Target]=@MeanGrade_Target, " +
                    "[TotalMarks]=@TotalMarks, " +
                    "[TotalPoints]=@TotalPoints, " +
                    "[Position]=@Position, " +
                    "[MeanMarks]=@MeanMarks, " +
                    "[MeanGrade]=@MeanGrade, " +
                    "[ClassTeacherRemark]=@ClassTeacherRemark, " +
                    "[HeadTeacherRemark]=@HeadTeacherRemark, " +
                    "[Status]=@Status, " +
                    "[IsDeleted]=@IsDeleted " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@StudentId", DbType.Int32, studentsExamResults_Temp.StudentId);
                db.AddInParameter(cmd, "@Examid", DbType.Int32, studentsExamResults_Temp.Examid);
                db.AddInParameter(cmd, "@SchoolClassId", DbType.Int32, studentsExamResults_Temp.SchoolClassId);
                db.AddInParameter(cmd, "@TeacherId", DbType.Int32, studentsExamResults_Temp.TeacherId);
                db.AddInParameter(cmd, "@TotalMarks_Target", DbType.Double, studentsExamResults_Temp.TotalMarks_Target);
                db.AddInParameter(cmd, "@TotalPoints_Target", DbType.Double, studentsExamResults_Temp.TotalPoints_Target);
                db.AddInParameter(cmd, "@Position_Target", DbType.Int32, studentsExamResults_Temp.Position_Target);
                db.AddInParameter(cmd, "@MeanMarks_Target", DbType.Double, studentsExamResults_Temp.MeanMarks_Target);
                db.AddInParameter(cmd, "@MeanGrade_Target", DbType.String, studentsExamResults_Temp.MeanGrade_Target);
                db.AddInParameter(cmd, "@TotalMarks", DbType.Double, studentsExamResults_Temp.TotalMarks);
                db.AddInParameter(cmd, "@TotalPoints", DbType.Double, studentsExamResults_Temp.TotalPoints);
                db.AddInParameter(cmd, "@Position", DbType.Int32, studentsExamResults_Temp.Position);
                db.AddInParameter(cmd, "@MeanMarks", DbType.Double, studentsExamResults_Temp.MeanMarks);
                db.AddInParameter(cmd, "@MeanGrade", DbType.String, studentsExamResults_Temp.MeanGrade);
                db.AddInParameter(cmd, "@ClassTeacherRemark", DbType.String, studentsExamResults_Temp.ClassTeacherRemark);
                db.AddInParameter(cmd, "@HeadTeacherRemark", DbType.String, studentsExamResults_Temp.HeadTeacherRemark);
                db.AddInParameter(cmd, "@Status", DbType.StringFixedLength, studentsExamResults_Temp.Status);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, studentsExamResults_Temp.IsDeleted);
                db.AddInParameter(cmd, "@Id", DbType.Int32, studentsExamResults_Temp.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the StudentsExamResults_Temp table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.StudentsExamResults_Temp " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the StudentsExamResults_Temp table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A StudentsExamResults_Temp object with data populated from the database.</returns>
        public StudentsExamResults_Temp SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [StudentId], [Examid], [SchoolClassId], [TeacherId], [TotalMarks_Target], [TotalPoints_Target]" +
                        ", [Position_Target], [MeanMarks_Target], [MeanGrade_Target], [TotalMarks], [TotalPoints]" +
                        ", [Position], [MeanMarks], [MeanGrade], [ClassTeacherRemark], [HeadTeacherRemark]" +
                        ", [Status], [IsDeleted] " +
                "FROM dbo.StudentsExamResults_Temp  " +
                "WHERE [Id]=@Id ";

            StudentsExamResults_Temp studentsExamResults_Temp = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new StudentsExamResults_Temp
                        studentsExamResults_Temp = new StudentsExamResults_Temp();

                        // Read values.
                        studentsExamResults_Temp.Id = base.GetDataValue<int>(dr, "Id");
                        studentsExamResults_Temp.StudentId = base.GetDataValue<int>(dr, "StudentId");
                        studentsExamResults_Temp.Examid = base.GetDataValue<int>(dr, "Examid");
                        studentsExamResults_Temp.SchoolClassId = base.GetDataValue<int>(dr, "SchoolClassId");
                        studentsExamResults_Temp.TeacherId = base.GetDataValue<int>(dr, "TeacherId");
                        studentsExamResults_Temp.TotalMarks_Target = base.GetDataValue<double>(dr, "TotalMarks_Target");
                        studentsExamResults_Temp.TotalPoints_Target = base.GetDataValue<double>(dr, "TotalPoints_Target");
                        studentsExamResults_Temp.Position_Target = base.GetDataValue<int>(dr, "Position_Target");
                        studentsExamResults_Temp.MeanMarks_Target = base.GetDataValue<double>(dr, "MeanMarks_Target");
                        studentsExamResults_Temp.MeanGrade_Target = base.GetDataValue<string>(dr, "MeanGrade_Target");
                        studentsExamResults_Temp.TotalMarks = base.GetDataValue<double>(dr, "TotalMarks");
                        studentsExamResults_Temp.TotalPoints = base.GetDataValue<double>(dr, "TotalPoints");
                        studentsExamResults_Temp.Position = base.GetDataValue<int>(dr, "Position");
                        studentsExamResults_Temp.MeanMarks = base.GetDataValue<double>(dr, "MeanMarks");
                        studentsExamResults_Temp.MeanGrade = base.GetDataValue<string>(dr, "MeanGrade");
                        studentsExamResults_Temp.ClassTeacherRemark = base.GetDataValue<string>(dr, "ClassTeacherRemark");
                        studentsExamResults_Temp.HeadTeacherRemark = base.GetDataValue<string>(dr, "HeadTeacherRemark");
                        studentsExamResults_Temp.Status = base.GetDataValue<string>(dr, "Status");
                        studentsExamResults_Temp.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");
                    }
                }
            }

            return studentsExamResults_Temp;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the StudentsExamResults_Temp table.
        /// </summary>
        /// <returns>A collection of StudentsExamResults_Temp objects.</returns>		
        public List<StudentsExamResults_Temp> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [StudentId], [Examid], [SchoolClassId], [TeacherId], [TotalMarks_Target], [TotalPoints_Target]" +
                        ", [Position_Target], [MeanMarks_Target], [MeanGrade_Target], [TotalMarks], [TotalPoints]" +
                        ", [Position], [MeanMarks], [MeanGrade], [ClassTeacherRemark], [HeadTeacherRemark]" +
                        ", [Status], [IsDeleted] " +
                "FROM dbo.StudentsExamResults_Temp ";

            List<StudentsExamResults_Temp> result = new List<StudentsExamResults_Temp>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new StudentsExamResults_Temp
                        StudentsExamResults_Temp studentsExamResults_Temp = new StudentsExamResults_Temp();

                        // Read values.
                        studentsExamResults_Temp.Id = base.GetDataValue<int>(dr, "Id");
                        studentsExamResults_Temp.StudentId = base.GetDataValue<int>(dr, "StudentId");
                        studentsExamResults_Temp.Examid = base.GetDataValue<int>(dr, "Examid");
                        studentsExamResults_Temp.SchoolClassId = base.GetDataValue<int>(dr, "SchoolClassId");
                        studentsExamResults_Temp.TeacherId = base.GetDataValue<int>(dr, "TeacherId");
                        studentsExamResults_Temp.TotalMarks_Target = base.GetDataValue<double>(dr, "TotalMarks_Target");
                        studentsExamResults_Temp.TotalPoints_Target = base.GetDataValue<double>(dr, "TotalPoints_Target");
                        studentsExamResults_Temp.Position_Target = base.GetDataValue<int>(dr, "Position_Target");
                        studentsExamResults_Temp.MeanMarks_Target = base.GetDataValue<double>(dr, "MeanMarks_Target");
                        studentsExamResults_Temp.MeanGrade_Target = base.GetDataValue<string>(dr, "MeanGrade_Target");
                        studentsExamResults_Temp.TotalMarks = base.GetDataValue<double>(dr, "TotalMarks");
                        studentsExamResults_Temp.TotalPoints = base.GetDataValue<double>(dr, "TotalPoints");
                        studentsExamResults_Temp.Position = base.GetDataValue<int>(dr, "Position");
                        studentsExamResults_Temp.MeanMarks = base.GetDataValue<double>(dr, "MeanMarks");
                        studentsExamResults_Temp.MeanGrade = base.GetDataValue<string>(dr, "MeanGrade");
                        studentsExamResults_Temp.ClassTeacherRemark = base.GetDataValue<string>(dr, "ClassTeacherRemark");
                        studentsExamResults_Temp.HeadTeacherRemark = base.GetDataValue<string>(dr, "HeadTeacherRemark");
                        studentsExamResults_Temp.Status = base.GetDataValue<string>(dr, "Status");
                        studentsExamResults_Temp.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");

                        // Add to List.
                        result.Add(studentsExamResults_Temp);
                    }
                }
            }

            return result;
        }
    }
}

