//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:25:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSchoolWeb.Entities;

namespace SBiSchoolWeb.Data
{
    /// <summary>
    /// TimeTables data access component. Manages CRUD operations for the TimeTables table.
    /// </summary>
    public partial class TimeTableDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the TimeTables table.
        /// </summary>
        /// <param name="timeTable">A TimeTable object.</param>
        /// <returns>An updated TimeTable object.</returns>
        public TimeTable Create(TimeTable timeTable)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.TimeTables ([ClassStreamId], [ClassTimeTableXML], [IsDeleted]) " +
                "VALUES(@ClassStreamId, @ClassTimeTableXML, @IsDeleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ClassStreamId", DbType.Int32, timeTable.ClassStreamId);
                db.AddInParameter(cmd, "@ClassTimeTableXML", DbType.AnsiString, timeTable.ClassTimeTableXML);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, timeTable.IsDeleted);

                // Get the primary key value.
                timeTable.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return timeTable;
        }

        /// <summary>
        /// Updates an existing row in the TimeTables table.
        /// </summary>
        /// <param name="timeTable">A TimeTable entity object.</param>
        public void UpdateById(TimeTable timeTable)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.TimeTables " +
                "SET " +
                    "[ClassStreamId]=@ClassStreamId, " +
                    "[ClassTimeTableXML]=@ClassTimeTableXML, " +
                    "[IsDeleted]=@IsDeleted " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ClassStreamId", DbType.Int32, timeTable.ClassStreamId);
                db.AddInParameter(cmd, "@ClassTimeTableXML", DbType.AnsiString, timeTable.ClassTimeTableXML);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, timeTable.IsDeleted);
                db.AddInParameter(cmd, "@Id", DbType.Int32, timeTable.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the TimeTables table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.TimeTables " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the TimeTables table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A TimeTable object with data populated from the database.</returns>
        public TimeTable SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [ClassStreamId], [ClassTimeTableXML], [IsDeleted] " +
                "FROM dbo.TimeTables  " +
                "WHERE [Id]=@Id ";

            TimeTable timeTable = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new TimeTable
                        timeTable = new TimeTable();

                        // Read values.
                        timeTable.Id = base.GetDataValue<int>(dr, "Id");
                        timeTable.ClassStreamId = base.GetDataValue<int>(dr, "ClassStreamId");
                        timeTable.ClassTimeTableXML = base.GetDataValue<string>(dr, "ClassTimeTableXML");
                        timeTable.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");
                    }
                }
            }

            return timeTable;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the TimeTables table.
        /// </summary>
        /// <returns>A collection of TimeTable objects.</returns>		
        public List<TimeTable> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [ClassStreamId], [ClassTimeTableXML], [IsDeleted] " +
                "FROM dbo.TimeTables ";

            List<TimeTable> result = new List<TimeTable>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new TimeTable
                        TimeTable timeTable = new TimeTable();

                        // Read values.
                        timeTable.Id = base.GetDataValue<int>(dr, "Id");
                        timeTable.ClassStreamId = base.GetDataValue<int>(dr, "ClassStreamId");
                        timeTable.ClassTimeTableXML = base.GetDataValue<string>(dr, "ClassTimeTableXML");
                        timeTable.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");

                        // Add to List.
                        result.Add(timeTable);
                    }
                }
            }

            return result;
        }
    }
}

