//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:25:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiSchoolWeb.Entities;

namespace SBiSchoolWeb.Data
{
    /// <summary>
    /// Transport data access component. Manages CRUD operations for the Transport table.
    /// </summary>
    public partial class TransportDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the Transport table.
        /// </summary>
        /// <param name="transport">A Transport object.</param>
        /// <returns>An updated Transport object.</returns>
        public Transport Create(Transport transport)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.Transport ([ResidenceId], [Amount], [IsDeleted]) " +
                "VALUES(@ResidenceId, @Amount, @IsDeleted); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ResidenceId", DbType.Int32, transport.ResidenceId);
                db.AddInParameter(cmd, "@Amount", DbType.Currency, transport.Amount);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, transport.IsDeleted);

                // Get the primary key value.
                transport.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return transport;
        }

        /// <summary>
        /// Updates an existing row in the Transport table.
        /// </summary>
        /// <param name="transport">A Transport entity object.</param>
        public void UpdateById(Transport transport)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.Transport " +
                "SET " +
                    "[ResidenceId]=@ResidenceId, " +
                    "[Amount]=@Amount, " +
                    "[IsDeleted]=@IsDeleted " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ResidenceId", DbType.Int32, transport.ResidenceId);
                db.AddInParameter(cmd, "@Amount", DbType.Currency, transport.Amount);
                db.AddInParameter(cmd, "@IsDeleted", DbType.Boolean, transport.IsDeleted);
                db.AddInParameter(cmd, "@Id", DbType.Int32, transport.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the Transport table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.Transport " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the Transport table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A Transport object with data populated from the database.</returns>
        public Transport SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [ResidenceId], [Amount], [IsDeleted] " +
                "FROM dbo.Transport  " +
                "WHERE [Id]=@Id ";

            Transport transport = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new Transport
                        transport = new Transport();

                        // Read values.
                        transport.Id = base.GetDataValue<int>(dr, "Id");
                        transport.ResidenceId = base.GetDataValue<int>(dr, "ResidenceId");
                        transport.Amount = base.GetDataValue<decimal>(dr, "Amount");
                        transport.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");
                    }
                }
            }

            return transport;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the Transport table.
        /// </summary>
        /// <returns>A collection of Transport objects.</returns>		
        public List<Transport> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [ResidenceId], [Amount], [IsDeleted] " +
                "FROM dbo.Transport ";

            List<Transport> result = new List<Transport>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new Transport
                        Transport transport = new Transport();

                        // Read values.
                        transport.Id = base.GetDataValue<int>(dr, "Id");
                        transport.ResidenceId = base.GetDataValue<int>(dr, "ResidenceId");
                        transport.Amount = base.GetDataValue<decimal>(dr, "Amount");
                        transport.IsDeleted = base.GetDataValue<bool>(dr, "IsDeleted");

                        // Add to List.
                        result.Add(transport);
                    }
                }
            }

            return result;
        }
    }
}

