//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:22:08 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSchoolWeb.Entities
{
    /// <summary>
    /// Represents a row of ClassSubject data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class ClassSubject
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember] 
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ClassId column.
        /// </summary>
        [DataMember]
        public int ClassId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the SubjectCode column.
        /// </summary>
        [DataMember]
        public string SubjectCode { get; set; }

        /// <summary>
        /// Gets or sets a int value for the SubjectTeacherId column.
        /// </summary>
        [DataMember]
        public int SubjectTeacherId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Room column.
        /// </summary>
        [DataMember]
        public string Room { get; set; }

        /// <summary>
        /// Gets or sets a char value for the Status column.
        /// </summary>
        [DataMember]
        public char Status { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }
    }
}
