//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:22:08 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSchoolWeb.Entities
{
    /// <summary>
    /// Represents a row of MarksheetArchive data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class MarksheetArchive
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember] 
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Year column.
        /// </summary>
        [DataMember]
        public int Year { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Term column.
        /// </summary>
        [DataMember]
        public int Term { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ExamType column.
        /// </summary>
        [DataMember]
        public string ExamType { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Class column.
        /// </summary>
        [DataMember]
        public string Class { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Teacher column.
        /// </summary>
        [DataMember]
        public int Teacher { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Student column.
        /// </summary>
        [DataMember]
        public int Student { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Subject column.
        /// </summary>
        [DataMember]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Mark column.
        /// </summary>
        [DataMember]
        public int Mark { get; set; }

        /// <summary>
        /// Gets or sets a int value for the OutOf column.
        /// </summary>
        [DataMember]
        public int OutOf { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Grade column.
        /// </summary>
        [DataMember]
        public string Grade { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }
    }
}
