//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:22:08 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSchoolWeb.Entities
{
    /// <summary>
    /// Represents a row of Parent data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Parent
    {
        /// <summary>
        /// Gets or sets a int value for the ParentId column.
        /// </summary>
        [DataMember] 
        public int ParentId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Name column.
        /// </summary>
        [DataMember]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a char value for the Gender column.
        /// </summary>
        [DataMember]
        public char Gender { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CellPhoneNo column.
        /// </summary>
        [DataMember]
        public string CellPhoneNo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Occupation column.
        /// </summary>
        [DataMember]
        public string Occupation { get; set; }

        /// <summary>
        /// Gets or sets a char value for the Maritalstatus column.
        /// </summary>
        [DataMember]
        public char Maritalstatus { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Relationship column.
        /// </summary>
        [DataMember]
        public string Relationship { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }
    }
}
