//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:22:08 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSchoolWeb.Entities
{
    /// <summary>
    /// Represents a row of RoleRight data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class RoleRight
    {
        /// <summary>
        /// Gets or sets a int value for the RoleRightId column.
        /// </summary>
        [DataMember] 
        public int RoleRightId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the RoleId column.
        /// </summary>
        [DataMember]
        public string RoleId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Object column.
        /// </summary>
        [DataMember]
        public string Object { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ObjectType column.
        /// </summary>
        [DataMember]
        public string ObjectType { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ObjectRight column.
        /// </summary>
        [DataMember]
        public string ObjectRight { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }
    }
}
