//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 06:22:08 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSchoolWeb.Entities
{
    /// <summary>
    /// Represents a row of RuleSet data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class RuleSet
    {
        /// <summary>
        /// Gets or sets a string value for the Name column.
        /// </summary>
        [DataMember] 
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a int value for the MajorVersion column.
        /// </summary>
        [DataMember] 
        public int MajorVersion { get; set; }

        /// <summary>
        /// Gets or sets a int value for the MinorVersion column.
        /// </summary>
        [DataMember] 
        public int MinorVersion { get; set; }

        /// <summary>
        /// Gets or sets a string value for the RuleSet column.
        /// </summary>
        [DataMember]
        public string _RuleSet { get; set; }

        /// <summary>
        /// Gets or sets a short value for the Status column.
        /// </summary>
        [DataMember]
        public short Status { get; set; }

        /// <summary>
        /// Gets or sets a string value for the AssemblyPath column.
        /// </summary>
        [DataMember]
        public string AssemblyPath { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ActivityName column.
        /// </summary>
        [DataMember]
        public string ActivityName { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ModifiedDate column.
        /// </summary>
        [DataMember]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }
    }
}
