//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 01/14/2015 19:02:37 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiSchoolWeb.Entities
{
    /// <summary>
    /// Represents a row of Teacher data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Teacher
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Name column.
        /// </summary>
        [DataMember]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the IDNo column.
        /// </summary>
        [DataMember]
        public string IDNo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the TSCNo column.
        /// </summary>
        [DataMember]
        public string TSCNo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Position column.
        /// </summary>
        [DataMember]
        public string Position { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Status column.
        /// </summary>
        [DataMember]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateJoined column.
        /// </summary>
        [DataMember]
        public DateTime DateJoined { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateLeft column.
        /// </summary>
        [DataMember]
        public DateTime DateLeft { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsLeft column.
        /// </summary>
        [DataMember]
        public bool IsLeft { get; set; }

        /// <summary>
        /// Gets or sets a string value for the HighestQualification column.
        /// </summary>
        [DataMember]
        public string HighestQualification { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }
    }
}
